### ISSUE TITLE
HTTPS, github

### ISSUE THREAD

**Issue by Beanow** [teamopen-dev/shared-sourcecred#3]
Github may be caching, but won't give a letsencrypt cert yet.
Try again later.

**Comment by Beanow** [comment]
Github did not like that I initially created a CNAME record from `sourcecred.teamopen.dev` to `teamopen.dev`, where `teamopen.dev` had the A records for GitHubs servers.

After changing this to be a CNAME from `sourcecred.teamopen.dev` to `teamopen-dev.github.io` it finally worked.

**Comment by nothingismagick** [comment]
That is important knowledge.

>
